"""Report Service for FinSight Multi-Agent Research System (Sprint 10.4).

Manages CRUD operations, deterministic Markdown report compilation, and integration
with the verified FinancialResearchService pipeline.
"""

import logging
import uuid
from typing import Any
from sqlalchemy import select, delete, desc
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from app.core.database import async_session
from app.core.exceptions import NotFoundError, ValidationError
from app.models.report import Report
from app.schemas.report import CreateReportRequest, ReportResponse, ReportListResponse
from app.schemas.rag import CitationResponse
from app.agents.state import ResearchState, FinancialFinding

logger = logging.getLogger("finsight.services.report_service")


class ReportService:
    """Service handling financial research report lifecycle and Markdown formatting."""

    def __init__(self, session_factory: async_sessionmaker[AsyncSession] | None = None):
        self.session_factory = session_factory or async_session

    @classmethod
    def compile_markdown_report(
        cls,
        title: str,
        query: str,
        state: ResearchState,
    ) -> str:
        """
        Deterministically compile full publication-ready GitHub Flavored Markdown report
        from already verified ResearchState without performing arithmetic or extra LLM calls.
        """
        lines: list[str] = []
        lines.append(f"# Financial Research Report: {title}")
        lines.append("*Generated by FinSight Multi-Agent Research System*\n")

        # 1. Executive Summary
        lines.append("## 1. Executive Summary")
        summary = state.get("final_answer") or "No executive summary available."
        lines.append(f"{summary}\n")

        # 2. Key Financial Metrics & Calculated Ratios
        findings: list[FinancialFinding] = state.get("findings", [])
        
        # Filter raw and ratio metrics (exclude trend, comparison, cagr for specialized sections)
        standard_findings = [
            f for f in findings
            if not f.metric.endswith("_growth")
            and not f.metric.endswith("_cagr")
            and not f.metric.endswith("_trend")
            and "_comparison" not in f.metric
            and "_absolute_difference" not in f.metric
        ]

        if standard_findings:
            lines.append("## 2. Key Financial Metrics & Calculated Ratios")
            lines.append("| Document | Metric | Period | Value | Unit | Formula / Calculation |")
            lines.append("|---|---|---|---|---|---|")
            for f in standard_findings:
                doc_str = str(f.document_id)[:8] if f.document_id else "Primary"
                calc_str = f.calculation if f.calculation else "Reported Line Item"
                val_str = f"{f.value:,.2f}" if isinstance(f.value, (int, float)) else str(f.value)
                lines.append(f"| {doc_str} | {f.metric} | {f.period} | {val_str} | {f.unit} | {calc_str} |")
            lines.append("")

        # 3. Historical Trends & CAGR Analysis
        time_series_findings = [
            f for f in findings
            if f.metric.endswith("_growth") or f.metric.endswith("_cagr") or f.metric.endswith("_trend")
        ]

        if time_series_findings:
            lines.append("## 3. Historical Trends & CAGR Analysis")
            lines.append("| Document | Metric Analysis | Period Range | Value | Unit | Formula / Classification |")
            lines.append("|---|---|---|---|---|---|")
            for f in time_series_findings:
                doc_str = str(f.document_id)[:8] if f.document_id else "Primary"
                calc_str = f.calculation if f.calculation else "Time-Series Derivation"
                val_str = f"{f.value:,.2f}" if isinstance(f.value, (int, float)) else str(f.value)
                lines.append(f"| {doc_str} | {f.metric} | {f.period} | {val_str} | {f.unit} | {calc_str} |")
            lines.append("")

        # 4. Cross-Document & Peer Comparison
        comparison_findings = [
            f for f in findings
            if "_comparison" in f.metric or "_absolute_difference" in f.metric
        ]

        if comparison_findings:
            lines.append("## 4. Cross-Document & Peer Comparison")
            lines.append("| Comparative Metric | Comparison Scope | Value | Unit | Variance Formula |")
            lines.append("|---|---|---|---|---|")
            for f in comparison_findings:
                calc_str = f.calculation if f.calculation else "Cross-Document Diff"
                val_str = f"{f.value:,.2f}" if isinstance(f.value, (int, float)) else str(f.value)
                lines.append(f"| {f.metric} | {f.period} | {val_str} | {f.unit} | {calc_str} |")
            lines.append("")

        # 5. Source Evidence & Citations
        citations = state.get("citations", [])
        lines.append("## 5. Source Evidence & Citations")
        if citations:
            for idx, c in enumerate(citations, 1):
                doc_info = f"Document `{str(c.document_id)[:8]}`" if c.document_id else "Indexed Filing"
                page_info = f"Page {c.page_number}" if c.page_number else "Page N/A"
                stmt_info = f"Statement: `{c.statement_type}`" if c.statement_type else f"Type: `{c.chunk_type}`"
                lines.append(f"- **[SOURCE {idx}]**: {doc_info}, {page_info}, {stmt_info} (Chunk ID: `{str(c.chunk_id)[:8]}`)")
        else:
            lines.append("- *No document citations recorded for this inquiry.*")

        return "\n".join(lines)

    async def create_report_record(
        self,
        request: CreateReportRequest,
        db: AsyncSession | None = None,
    ) -> Report:
        """Create initial Report record in pending status."""
        title = request.title.strip() if request.title and request.title.strip() else f"Research: {request.query.strip()[:60]}"
        doc_ids_serialized = [str(d) for d in request.document_ids] if request.document_ids else None
        report = Report(
            title=title,
            query=request.query.strip(),
            report_type=request.report_type,
            status="pending",
            document_ids=doc_ids_serialized,
        )

        if db:
            db.add(report)
            await db.commit()
            await db.refresh(report)
            return report

        async with self.session_factory() as session:
            session.add(report)
            await session.commit()
            await session.refresh(report)
            return report

    async def get_report(self, report_id: uuid.UUID, db: AsyncSession | None = None) -> Report:
        """Retrieve a Report record by UUID."""
        if db:
            stmt = select(Report).where(Report.id == report_id)
            result = await db.execute(stmt)
            report = result.scalar_one_or_none()
            if not report:
                raise NotFoundError(f"Report not found with ID {report_id}")
            return report

        async with self.session_factory() as session:
            stmt = select(Report).where(Report.id == report_id)
            result = await session.execute(stmt)
            report = result.scalar_one_or_none()
            if not report:
                raise NotFoundError(f"Report not found with ID {report_id}")
            return report

    async def list_reports(
        self,
        status: str | None = None,
        limit: int = 50,
        offset: int = 0,
        db: AsyncSession | None = None,
    ) -> ReportListResponse:
        """List reports sorted newest first with optional status filtering."""
        if limit < 1 or limit > 100:
            raise ValidationError("Limit must be between 1 and 100")
        if offset < 0:
            raise ValidationError("Offset must be non-negative")

        query_stmt = select(Report)
        if status:
            query_stmt = query_stmt.where(Report.status == status)
        query_stmt = query_stmt.order_by(desc(Report.created_at)).offset(offset).limit(limit)

        if db:
            result = await db.execute(query_stmt)
            items = result.scalars().all()
        else:
            async with self.session_factory() as session:
                result = await session.execute(query_stmt)
                items = result.scalars().all()

        responses = [self._format_report_response(r) for r in items]
        return ReportListResponse(total=len(responses), reports=responses)

    async def delete_report(self, report_id: uuid.UUID, db: AsyncSession | None = None) -> None:
        """Delete a report record without affecting source documents or chunks."""
        if db:
            report = await self.get_report(report_id, db=db)
            await db.delete(report)
            await db.commit()
            return

        async with self.session_factory() as session:
            report = await self.get_report(report_id, db=session)
            await session.delete(report)
            await session.commit()

    @classmethod
    def _format_report_response(cls, report: Report) -> ReportResponse:
        """Convert SQLAlchemy Report instance to Pydantic ReportResponse."""
        citations = None
        if report.citations:
            citations = [CitationResponse(**c) for c in report.citations]

        # Parse document_ids safely if stored as strings/UUIDs in JSONB
        doc_ids = None
        if report.document_ids:
            doc_ids = [uuid.UUID(str(d)) for d in report.document_ids]

        return ReportResponse(
            id=report.id,
            title=report.title,
            query=report.query,
            report_type=report.report_type,
            status=report.status,
            document_ids=doc_ids,
            executive_summary=report.executive_summary,
            findings=report.findings,
            content=report.content,
            citations=citations,
            error_message=report.error_message,
            created_at=report.created_at,
            updated_at=report.updated_at,
        )
