"""LangGraph State and Structured Data Contracts for FinSight Multi-Agent Research System (Sprint 9.1)."""

from typing import TypedDict, Any
from uuid import UUID
from pydantic import BaseModel, Field

from app.services.retrieval_service import RetrievalResult
from app.services.rag_service import SourceCitation


class PlannerOutput(BaseModel):
    """Structured output produced by the Planner Node."""
    sub_queries: list[str] = Field(
        default_factory=list,
        description="Bounded list of focused retrieval sub-queries decomposed from research request",
    )
    rationale: str = Field(
        "",
        description="Concise rationale explaining the decomposition strategy",
    )


class FinancialFinding(BaseModel):
    """Structured financial metric or calculated ratio produced by the Financial Analyzer Node."""
    metric: str = Field(..., description="Canonical metric name (e.g. 'revenue', 'gross_profit', 'gross_margin')")
    period: str = Field(..., description="Fiscal period or year (e.g. '2025', '2024', 'Q3')")
    value: float = Field(..., description="Numerical figure extracted or computed")
    unit: str = Field("$", description="Unit or currency (e.g. '$', '%', 'shares', 'ratio')")
    source_chunk_ids: list[UUID] = Field(
        default_factory=list,
        description="Chunk UUIDs backing this numerical finding",
    )
    calculation: str | None = Field(
        None,
        description="Deterministic formula if calculated (e.g. 'gross_profit / revenue * 100')",
    )


class FinancialAnalysis(BaseModel):
    """Collection of findings and comparisons generated by the Financial Analyzer Node."""
    findings: list[FinancialFinding] = Field(
        default_factory=list,
        description="Verified financial metrics and ratio calculations",
    )
    insights: list[str] = Field(
        default_factory=list,
        description="Factual comparative statements backed by findings",
    )


class AuditedFinding(BaseModel):
    """Individual finding verification record produced by the Citation Auditor / Critic Node."""
    metric: str
    period: str
    value: float
    supported: bool
    source_chunk_ids: list[UUID]
    audit_notes: str


class CitationAuditResult(BaseModel):
    """Complete audit report produced by the Citation Auditor / Critic Node."""
    passed: bool = Field(..., description="True if at least one finding was verified against retrieved chunks")
    audited_findings: list[AuditedFinding] = Field(
        default_factory=list,
        description="List of verified and backed financial findings",
    )
    unsupported_findings: list[str] = Field(
        default_factory=list,
        description="Explanations of unverified or hallucinated findings rejected by the auditor",
    )


class ResearchState(TypedDict):
    """Type-safe state graph passed across LangGraph nodes."""
    session_id: UUID | None
    original_query: str
    standalone_query: str
    document_id: UUID | None
    top_k: int
    min_similarity: float
    sub_queries: list[str]
    retrieved_chunks: list[RetrievalResult]
    findings: list[FinancialFinding]
    citation_audit: CitationAuditResult | None
    guardrails_validation: Any | None
    final_answer: str | None
    citations: list[SourceCitation]
    grounded: bool
    step_count: int
    status: str
    error: str | None
